# Generated by Django 5.0.3 on 2024-03-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='apellido_Prov',
            field=models.CharField(default='apellido proveedor', max_length=100, verbose_name='Apellido del Proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dni_Prov',
            field=models.IntegerField(default=2, max_length=3, verbose_name='Dni del Proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_Prov',
            field=models.CharField(default='nombre proveedor', max_length=100, verbose_name='Nombre del Proveedor'),
        ),
    ]
