# Generated by Django 5.0.3 on 2024-03-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_proveedor_apellido_prov_proveedor_dni_prov_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='dni_Prov',
            field=models.IntegerField(default=0, max_length=3, verbose_name='Dni del Proveedor'),
        ),
    ]
