# Generated by Django 5.0.3 on 2024-03-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_alter_proveedor_dni_prov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_Prod',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
    ]
