# Generated by Django 5.0.3 on 2024-03-25 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0007_alter_producto_stock_actual_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_Prod',
            field=models.CharField(default='', max_length=100, verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='compra.proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='apellido_Prov',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_Prov',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre'),
        ),
    ]
