# Generated by Django 5.0.3 on 2024-04-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0012_alter_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_Prod',
            field=models.CharField(default='Null', max_length=100, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_Prov',
            field=models.CharField(default='Null', max_length=100, verbose_name='Nombre'),
        ),
    ]
