# Generated by Django 5.0.3 on 2024-04-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0013_alter_producto_nombre_prod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_Prod',
            new_name='nombre_prod',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_Prod',
            new_name='precio_prod',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='proveedor',
            new_name='proveedor_prod',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='stock_actual_Prod',
            new_name='stock_actual_prod',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='apellido_Prov',
            new_name='apellido_prov',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='dni_Prov',
            new_name='dni_prov',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre_Prov',
            new_name='nombre_prov',
        ),
    ]
